build_server:
	cc 1.udp_server.c -o server
 

build_client:
	cc 1.udp_client.c -o client

run_server:
	./server

run_client:
	./client 

run_clients:
	./client  &
	./client  &
	./client  &
	./client  &
	./client  &
	./client  &
	./client  &
	./client  &
	./client  &
	./client  &
	