build_get:
	cc 1.get_info.c -o get

build_send:
	cc 2.send_sig.c -o send

build_send_all:
	cc 4.send_all.c -o send_all

build_block:
	cc 3.sig_block.c -o block

run_get:
	./get

run_block:
	./block

run_send:
	./send

run_send_all:
	./send_all



#录屏作业:
#讲解各种进程间通信技术的基本模型